export const Notific = [
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText:
      'stristrinstringstringstring stringgstrinstringstringstringstringgstrinstringstringstringstrinstrinsstrinstringsstrinsstrinstringstringstringstringgst rinstringstringstringstring gstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstringgtringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringsstrinsstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstringstrinsstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstringggtringgggng',
    message:
      'strinsstrinstringststrin sstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringg strinstringstringstringstringgtri ngstringstringstringgringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstrinstrinsstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstrinstrinsstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgstrinstringstringstringstringgtringstringstringstringggggg',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new friend request',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new friend request',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new friend request',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new Event created',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new Event created',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new Event created',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new achivement',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new achivement',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new achivement',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new achivement,',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'string',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'string',
    viewed: false
  },
  {
    actionUserId: 2,
    actionUserText: '',
    bodyText: 'string',
    message: 'string',
    notificationId: 23,
    notificationType: 'string',
    projectName: 'Greencity',
    secondMessage: 'string',
    secondMessageId: 3,
    targetId: 3,
    time: new Date(),
    titleText: 'new friend request',
    viewed: false
  }
];
