server {
    root /usr/share/nginx/html;
    index index.html;
    autoindex on;

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location ~* \.(?:js|css)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    error_page 404 /error.html;
}
