export enum OrderStatus {
  FORMED = 'FORMED',
  CANCELED = 'CANCELED',
  ON_THE_ROUTE = 'ON_THE_ROUTE',
  CONFIRMED = 'CONFIRMED',
  NOT_TAKEN_OUT = 'NOT_TAKEN_OUT',
  BROUGHT_IT_HIMSELF = 'BROUGHT_IT_HIMSELF',
  DONE = 'DONE',
  ADJUSTMENT = 'ADJUSTMENT'
}

export enum PaymnetStatus {
  PAID = 'PAID',
  HALF_PAID = 'HALF_PAID',
  UNPAID = 'UNPAID'
}
