export enum TableKeys {
  generalDiscount = 'generalDiscount',
  bagsAmount = 'bagsAmount',
  amountDue = 'amountDue',
  totalOrderSum = 'totalOrderSum',
  totalPayment = 'totalPayment',
  responsibleDriver = 'responsibleDriver',
  responsibleCaller = 'responsibleCaller',
  responsibleLogicMan = 'responsibleLogicMan',
  responsibleNavigator = 'responsibleNavigator',
  dateOfExport = 'dateOfExport',
  timeOfExport = 'timeOfExport',
  receivingStation = 'receivingStation',
  cancellationReason = 'cancellationReason',
  cancellationComment = 'cancellationComment',
  paymentDate = 'paymentDate',
  orderDate = 'orderDate',
  city = 'city',
  district = 'district',
  paymentDateFrom = 'paymentDateFrom',
  orderDateFrom = 'orderDateFrom',
  citiesEn = 'citiesEn',
  districtsEn = 'districtsEn',
  clientPhone = 'clientPhone',
  senderPhone = 'senderPhone'
}
